{ config, ... }: {
  imports = [
    ./attributes.nix
    ./user.nix
    ./home-manager.nix

    ./appearance/fonts
    ./appearance/stylix
    ./browsers
    ./dev/claudecode
    ./dev/cloud
    ./dev/direnv
    ./dev/dotnet
    ./dev/python
    ./dev/rust
    ./dev/git/core
    ./dev/ide/cursor
    ./dev/ide/rider
    ./dev/ide/vscode
    ./dev/shared
    ./emacs
    ./networking/core
    ./networking/ssh
    ./networking/tailscale
    ./networking/wireless
    ./nix/core
    ./shell/alacritty
    ./shell/bash
    ./shell/core
    ./shell/starship
    ./shell/tmux
    ./shell/tools
    ./virt/core
    ./virt/docker
    ./workstation/drives
    ./workstation/dunst
    ./workstation/flameshot
    ./workstation/rofi
    ./workstation/sound
    ./workstation/video/opengl
    ./workstation/keyring
    ./workstation/zathura
    ./wm/i3
  ];
}
